apiVersion: v2
name: podiumd-monitoring-logging
description: A Helm chart for deploying monitoring and logging
version: 1.0.0-alpha.1
appVersion: "1.0"

dependencies:
  - name: kube-prometheus-stack
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: loki
    repository: "https://grafana.github.io/helm-charts"
  - name: promtail
    repository: "https://grafana.github.io/helm-charts"
  - name: opentelemetry-collector
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  - name: tempo
    repository: "https://grafana.github.io/helm-charts"