---
# https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml

deploymentMode: SingleBinary

singleBinary:
  replicas: 2
  resources:
    requests:
      cpu: 50m
      memory: 384Mi
    limits:
      cpu: 500m
      memory: 1Gi
  nodeSelector:
    kubernetes.azure.com/mode: system

loki:
  image:
    registry: REP_ACR_NAME_REP.azurecr.io
    repository: loki
    tag: "3.1.0"
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: azure
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
    type: azure
    azure:
      accountKey: "REP_STORAGE_ACCOUNT_KEY_REP"
      accountName: REP_STORAGE_ACCOUNT_REP
      container: logs
      request_timeout: 0
  auth_enabled: false
  frontend:
    max_outstanding_per_tenant: 4096

gateway:
  enabled: true
  image:
    registry: REP_ACR_NAME_REP.azurecr.io
    repository: nginx
    tag: stable
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 50m
      memory: 32Mi
  nodeSelector:
    kubernetes.azure.com/mode: system

sidecar:
  image:
    registry: REP_ACR_NAME_REP.azurecr.io
    repository: REP_ACR_NAME_REP.azurecr.io/grafana-sidecar
    tag: 1.26.1
  dashboards:
    skipReload: true

resultsCache:
  enabled: false

chunksCache:
  enabled: false

write:
  replicas: 0

read:
  replicas: 0

backend:
  replicas: 0

# Keep log data up to 1 year
table_manager:
  retention_deletes_enabled: true
  retention_period: 365d

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  dashboards:
    enabled: false
  rules:
    enabled: false

test:
  enabled: false

lokiCanary:
  enabled: false
